name: Kontrol
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true
on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'  
jobs:
  BirlesikGuncelleme:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
      - name: Depoyu Klonla
        uses: actions/checkout@v4.2.2
        
      - name: Python 3.11.8 Yükle
        uses: actions/setup-python@v5.3.0
        with:
          python-version: 3.11.8
          
      - name: Gereksinimleri Kur
        run: |
          python -m pip install --upgrade pip
          pip install -U setuptools wheel Kekik httpx parsel requests cloudscraper beautifulsoup4
          
      - name: inn.py Çalıştır
        continue-on-error: true
        run: python inn.py
      - name: oki.py Çalıştır
        continue-on-error: true
        run: python oki.py  
      - name: an.py Çalıştır
        continue-on-error: true
        run: python an.py
      - name: s.py Çalıştır
        continue-on-error: true
        run: python selcuk.py
      - name: r.py Çalıştır
        continue-on-error: true
        run: python r.py
      - name: r2.py Çalıştır
        continue-on-error: true
        run: python r2.py
      - name: ftb.py Çalıştır
        continue-on-error: true
        run: python ftb.py
      - name: kbl.py Çalıştır
        continue-on-error: true
        run: python kbl.py        
      - name: rnl.py Çalıştır
        continue-on-error: true
        run: python rnl.py        
      - name: fll.py Çalıştır
        continue-on-error: true
        run: python fll.py 
      - name: int.py Çalıştır
        continue-on-error: true
        run: python int.py 
      - name: sc.py Çalıştır
        continue-on-error: true
        run: python sc.py 
      - name: jst.py Çalıştır
        continue-on-error: true
        run: python jst.py 
      - name: zs.py Çalıştır
        continue-on-error: true
        run: python zs.py 
      - name: msi.py Çalıştır
        continue-on-error: true
        run: python zs.py 
      - name: Değişiklik Kontrolü
        id: degisiklik_kontrol
        run: |
          git diff --quiet . || echo "degisiklik=true" >> $GITHUB_OUTPUT
          
      - name: Değişiklikleri Commit Et
        if: steps.degisiklik_kontrol.outputs.degisiklik == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "🔄 Kanallar güncellendi" -m "📺 Domain kontrolü ve M3U güncellemeleri tamamlandı" -m "🕒 Otomatik işlem - $GITHUB_SHA"
          git push
